// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOs5MxcyozVxxIlJt3JrhmRA-d9of228U',
    appId: '1:416892642366:android:faaf0af2835f1db53bdd6f',
    messagingSenderId: '416892642366',
    projectId: 'rosterie',
    storageBucket: 'rosterie.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtUSdN0jzsYK0qkd6MPIfQrWZpBXqKPVw',
    appId: '1:528530796279:ios:f0e39aa5bf818041d4adf2',
    messagingSenderId: '528530796279',
    projectId: 'roster-3fe4b',
    storageBucket: 'roster-3fe4b.firebasestorage.app',
    iosBundleId: 'com.example.Roster',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpMaXksq_uaABa2K5IqhIHJMkSbNvKWsw',
    authDomain: 'rosterie.firebaseapp.com',
    projectId: 'rosterie',
    storageBucket: 'rosterie.firebasestorage.app',
    messagingSenderId: '416892642366',
    appId: '1:416892642366:web:1f243571b625e7f73bdd6f',
    measurementId: 'G-KCY8NVNDNH',
  );
}
